import './globals.css'
import NavBar from '../components/NavBar'
import Footer from '../components/Footer'
import ScrollTopToButton from '../components/ScrollToTopButton'
import Provider from './providers'
import { Inter } from 'next/font/google'
import './styles/slick/slick.min.css'
import Script from 'next/script'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'You-i Lab |',
  description: 'Generated by You-i Lab',

}

export default function RootLayout({ children }) {
  const isClient = typeof window !== 'undefined';

  if (isClient) {
    // Importar y aplicar estilos solo en el lado del cliente
    import('./styles/slick/slick.min.css');
  }


  return (
    <html lang="es">
      <head>
        {/* link manifest.json */}

        <link rel="icon" type="image/svg+xml" href="/youilab_logo.svg" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link rel="preconnect" href="https://www.gstatic.com" />
        <link rel="preconnect" href="https://www.google.com" />

        <Script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.0.0/flowbite.min.js"></Script>




      </head>

      <body className={inter.className}>
        <Provider>
          <NavBar />
          {children}
          <ScrollTopToButton />
          <Footer />
        </Provider>
      </body>
    </html>
  )
}


